# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_alerta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alerta',
        ),
        migrations.AddField(
            model_name='instructor',
            name='mensaje',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
