# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_auto_20170919_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='titulo',
        ),
    ]
